# Generated by Django 3.1 on 2020-10-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_auto_20201023_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionproduct',
            name='hash',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='auctionproduct',
            name='txId',
            field=models.CharField(default=None, max_length=66, null=True),
        ),
    ]
